### ISSUE TITLE
Support oneOfType

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/prop-types-csharp#11]
Support `PropTypes.oneOfType` somehow.

**Comment by pellebjerkestrand** [comment]
I don't think this is possible in C#, at least not easily.

**Comment by pellebjerkestrand** [comment]
Or maybe one can do something like:

```js
const propTypes = {
   theProperty: PropTypes.oneOfType([PropTypes.string, PropTypes.number])
};
```

```csharp
public class Component<T> where T : string, int
{
   public T TheProperty { get;set; }
}
```

**Comment by pellebjerkestrand** [comment]
Aaaand, no. `string`, `int` etc. don't work. `A type used as a constraint must be an interface, a non-sealed class or a type parameter`.
