### ISSUE TITLE
Refactor enums

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/prop-types-csharp#28]
Refactor generated enums to look like this:

```
public enum Theme
{
  [EnumMember(Value = "-theme-blue")]
  ThemeBlue = 0
}
```

This requires the following import:

```
using System.Runtime.Serialization;
```

**Comment by Sriess** [comment]
This requires the use of **StringEnumConverter** to be set either directly on the enum like this:
```
[JsonConverter(typeof(StringEnumConverter))]
public enum Theme
{
  [EnumMember(Value = "-theme-blue")]
  ThemeBlue = 0
}
```
Or to set this globally in the Application_Start (here it is as a part of the ReactConfig):
```
ReactSiteConfiguration.Configuration
                .SetJsonSerializerSettings(new JsonSerializerSettings
                {
                    Converters = new List<JsonConverter> { new StringEnumConverter() }
                });
```
This requires using the namespace `using Newtonsoft.Json.Converters;`

**Comment by asbjornh** [comment]
Forgot to add Readme! Opening this agagin
