### ISSUE TITLE
PropTypes.exact

### ISSUE THREAD

**Issue by asbjornh** [Creuna-Oslo/prop-types-csharp#49]
Support it :D

**Comment by pellebjerkestrand** [comment]
I didn't even know this existed. Can we use the same code as for `shape`?

**Comment by asbjornh** [comment]
Yes, the generator can treat it the same way as a shape because `exact` is just a more strict version of shape (no extra properties allowed). Internally in `prop-types` it's actually called a [strict shape type checker](https://github.com/facebook/prop-types/blob/11e45c433f439940a4a6fa280a4464ef449e8943/factoryWithTypeCheckers.js#L132)
