### ISSUE TITLE
An `include` option

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/prop-types-csharp#60]
It would be nice to have an `include` option where one could specify which directories to include instead of having to specify many directories in `exclude`.

**Comment by asbjornh** [comment]
There is one. It’s called `match`

**Comment by pellebjerkestrand** [comment]
I didn't understand the documentation. I thought `match` was for filenames and not the whole path.

**Comment by asbjornh** [comment]
Hm. Well maybe the wording in the readme could be adjusted.

As far as I know all matching patterns in the webpack ecosystem work on whole paths though
