### ISSUE TITLE
Generate classes from things other than React components

### ISSUE THREAD

**Issue by pellebjerkestrand** [Creuna-Oslo/prop-types-csharp#61]
It would be nice if this could generate classes from things other than React components so that one could, f.ex., describe the expected shape of API results.

These classes could then be used by the server, and the response could be validated on the client.

**Comment by asbjornh** [comment]
Been thinking about this too. I think it’ll be tough getting full type safety, but the propTypes API can be called manually to validate API responses which is a start. The hard part is figuring out how to tell the generator where to look for api definitions.

**Comment by pellebjerkestrand** [comment]
> [...]the propTypes API can be called manually to validate API responses [...]
This is exactly what I want to use it for.

**Comment by asbjornh** [comment]
We might be able to solve this by exposing a function from this package, like:

```js
import { validate } from '@creuna/prop-types-csharp';

validate(
  "SomeCustomName",
  { foo: PropTypes.string },
  someObjectToValidate
);
```

which would call `PropTypes.checkPropTypes`, and could be used to generate:

```cs
public class SomeComponent { // component class }

public class SomeCustomName {
  public string Foo { get; set; }
}
```

This would tie all the things we need together. There's an issue though; we'd have a direct/peer dependency on `prop-types`, which is sort of lame since we have rudimentary support for typescript (which doesn't use `prop-types` at all) and I'd like to keep the door open to supporting any language that can be parsed by `babel`.

Alternatively we could do something like this which would avoid the dependency issue:

```js
validate(
  "SomeCustomName",
  PropTypes.checkPropTypes(
    { foo: PropTypes.string },
    someObjectToValidate,
    "property",
    "SomeCustomName"
  );
```

This is lame in several other ways though...

You got any thoughts on this @pellebjerkestrand ?

**Comment by asbjornh** [comment]
We might also have to think about how to support wrapping API responses in a way that we don't have to keep explicitly providing type definitions for stuff like `analytics` and `message` for every single API call.

**Comment by asbjornh** [comment]
> We might also have to think about how to support wrapping API responses in a way that we don't have to keep explicitly providing type definitions for stuff like `analytics` and `message` for every single API call.

We could potentially solve this by accepting the propTypes of another component as a "base class" to the function (similar to how component class extension works already):

```js
validate(
  { payload: PropTypes.exact({}) },
  response,
  "MyApiResponse",
  ResponseWrapper.propTypes // Both for validation and for getting the name of the base class
);
```

which would result in:

```cs
public class MyApiResponse : ResponseWrapper {
  public MyApiResponse_Payload Payload { get; set; }
}
```

and then have a `response-wrapper.jsx` that generates `ResponseWrapper.cs` (which would contain definitions for `analytics` and so on).

**Comment by pellebjerkestrand** [comment]
As long as one can generate classes for the payload, one can always implement the wrapper manually.

```csharp
public class ApiResponse<T> {
   public Analytics Analytics { get; set; }
   // Other metadata properties
   public T Payload { get; set; }
}
```
or  maybe wrap all the metadata in its own class
```csharp
public class ApiResponse<T> {
   public ApiMetadata Metadata { get; set; }
   public T Payload { get; set; }
}
```

**Comment by pellebjerkestrand** [comment]
Having `validate`or any other function like that in this package doesn't make sense to me. I'm just interested in generating the C# classes.

**Comment by asbjornh** [comment]
> Having `validate`or any other function like that in this package doesn't make sense to me. I'm just interested in generating the C# classes.

If the validation and the generated class aren't tied together (like they are with propTypes), then there's really no type safety at all. It's literally just a shortcut for typing out the C# class by hand. No guarantee of the build breaking when the client has made breaking changes to the API.

You can achieve what you're describing right now by adding an empty component that just specifies propTypes for the API response you want to describe, like:

```js
// some-api-response.jsx
Const SomeApiResponse = () => {};
SomeApiResponse.propTypes = { // definition };
export default SomeApiResponse;
```

If we're going to add something specific in this package I think it should have the same level of guarantees that the normal component stuff has.

**Comment by asbjornh** [comment]
Another approach might be that react-components call `PropTypes.checkPropTypes` directly and the identifier name of the validated object is used for naming the class property.

```js
const Component = () => {
  React.useEffect(() => {
    api.fetch("blabla").then(apiResponse => {
      PropTypes.checkPropTypes({ foo: PropTypes.string }, apiResponse);
    })
  });
};
```

Which would generate:

```cs
public class Component { /* ... */ }

public class Component_ApiResponse {
  public string Foo { get; set; }
}
```

Alternatively we could require the type definition to be an identifier and use that name instead.

**Comment by pellebjerkestrand** [comment]
> You can achieve what you're describing right now by adding an empty component that just specifies propTypes for the API response you want to describe, like:
> 
> ```js
> // some-api-response.jsx
> Const SomeApiResponse = () => {};
> SomeApiResponse.propTypes = { /*definition*/ };
> export default SomeApiResponse;
> ```

Yes, that's probably what we'll start out with. I would like to be able to just
```js
export default { /*definition*/ }
```
using perhaps the file name as the class name.

**Comment by asbjornh** [comment]
I'm going to close this for inactivity. Also I don't really agree that adding complexity to an already complex module just for the sake of saving two lines of source code is worth it.

For future reference, classes not tied to a react component can be generated like this:

```js
const SomeClass = {};
SomeClass.propTypes = { /* type definitions */ };
export default SomeClass;
```

This can be combined with the `match` option if you want to use `.js` file extensions, like:

```js
new PropTypesCSharpPlugin({
  match: [/\.jsx$/, /source\/other-view-models\/.+\.js$/]
})
```
